# Generated by Django 2.2.4 on 2019-08-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht6p', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='license',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='lname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='username',
            new_name='fname',
        ),
    ]
