# Generated by Django 2.2.4 on 2019-08-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht6p', '0002_auto_20190825_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='mbutton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
            ],
        ),
    ]
